const nodemailer = require('nodemailer');
require('dotenv').config();

// Configuration du transporteur Nodemailer (Simulation pour développement)
// En production, vous utiliseriez vos vrais identifiants SMTP via process.env
const transporter = nodemailer.createTransport({
  host: process.env.SMTP_HOST || 'smtp.ethereal.email',
  port: process.env.SMTP_PORT || 587,
  auth: {
    user: process.env.SMTP_USER || 'test-user@ethereal.email',
    pass: process.env.SMTP_PASS || 'test-pass'
  }
});

/**
 * Envoie un email d'alerte pour stock critique
 */
async function sendCriticalAlertEmail(products) {
  if (!products || products.length === 0) return;

  const productListHtml = products.map(p => 
    `<li><strong>${p.name}</strong>: Stock ${p.stock_actuel} (Seuil: ${p.min_threshold}, Cible: ${p.target_stock})</li>`
  ).join('');

  const mailOptions = {
    from: '"TTDJAPP Notifications" <noreply@ttdjapp.com>',
    to: process.env.MANAGER_EMAIL || 'responsable@ttdjapp.com', // Le responsable
    subject: `🚨 Alerte Stock Critique : ${products.length} produit(s) en rupture imminente`,
    html: `
      <h2>Alerte d'Inventaire</h2>
      <p>Les produits suivants ont atteint le niveau critique et nécessitent une commande :</p>
      <ul>
        ${productListHtml}
      </ul>
      <p>Veuillez vous connecter à l'application TTDJAPP pour générer un bon de commande.</p>
    `
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log('Email d\'alerte envoyé: %s', info.messageId);
  } catch (error) {
    console.error('Erreur lors de l\'envoi de l\'email d\'alerte:', error);
  }
}

/**
 * Envoie un email quand un Bon de Commande est généré automatiquement
 */
async function sendPOAutoGeneratedEmail(poId, itemsCount, totalEstimated) {
  const mailOptions = {
    from: '"TTDJAPP Notifications" <noreply@ttdjapp.com>',
    to: process.env.MANAGER_EMAIL || 'responsable@ttdjapp.com',
    subject: `📝 Nouveau Bon de Commande Auto-Généré (#${poId})`,
    html: `
      <h2>Bon de Commande Préparé</h2>
      <p>Un brouillon de bon de commande intelligent a été généré par le système.</p>
      <ul>
        <li><strong>N° Commande :</strong> ${poId}</li>
        <li><strong>Nombre d'articles :</strong> ${itemsCount}</li>
        <li><strong>Total Estimé :</strong> $${totalEstimated}</li>
      </ul>
      <p>Veuillez vous connecter pour le réviser et le valider.</p>
    `
  };

  try {
    const info = await transporter.sendMail(mailOptions);
    console.log('Email de BC envoyé: %s', info.messageId);
  } catch (error) {
    console.error('Erreur lors de l\'envoi de l\'email du BC:', error);
  }
}

module.exports = {
  sendCriticalAlertEmail,
  sendPOAutoGeneratedEmail
};
