const nodemailer = require('nodemailer');

class EmailService {
  constructor() {
    if (process.env.SMTP_HOST) {
      this.transporter = nodemailer.createTransport({
        host: process.env.SMTP_HOST,
        port: process.env.SMTP_PORT || 587,
        secure: process.env.SMTP_SECURE === 'true',
        auth: {
          user: process.env.SMTP_USER,
          pass: process.env.SMTP_PASS,
        },
      });
    } else {
      this.transporter = null;
    }
  }

  async sendPOAutoGeneratedEmail(poId, itemsCount, totalEstimated) {
    if (!this.transporter) {
      console.log(`[EmailService Mock] Notification for Auto-generated PO #${poId} with ${itemsCount} items.`);
      return;
    }

    const mailOptions = {
      from: process.env.SMTP_FROM || '"Admin" <admin@example.com>',
      to: process.env.ADMIN_EMAIL || 'admin@example.com',
      subject: `[Alerte Stock] Nouvelle Commande Automatique #${poId}`,
      text: `Une nouvelle commande a été générée automatiquement (ID: ${poId}) comprenant ${itemsCount} produits critiques.`,
    };

    try {
      await this.transporter.sendMail(mailOptions);
      console.log(`Email sent successfully for PO #${poId}`);
    } catch (error) {
      console.error('Error sending email:', error);
    }
  }
}

module.exports = new EmailService();
